In [5]:
import numpy as np
import pandas as pd

In [8]:
df = pd.read_csv('cleaned_PQC_train.csv')
df.head()

,Game_ID,Game_Name,Released_Year,Game_Type,Age_Category,Min_Players,Max_Players,Average_Complexity,Complexity_Raters,Average_Play_Time,Owner_Number,Trader_Number,HighInterest_Number,Interest_Number,Rater_Number,Comment_Number,Average_Rating
0,9048,NaN,2010.866185,BaseGame,under 5,2.063485,6.972730,3.393361,230.948365,122.783903,2645.455635,70.467538,295.440589,772.259070,1950.401281,666.936721,7.51948
1,40086,Going The Distance,1999.742001,BaseGame,under 5,2.024560,8.083061,1.986367,-31.604440,61.738091,-55.070871,-10.584828,8.237338,70.751003,94.752363,12.909037,7.50000
2,12545,Inside,2006.099268,BaseGame,5 to under 12,1.904577,2.252234,1.987593,-16.699059,7.007170,162.082429,23.156978,22.295290,43.073858,-28.294346,-36.402393,6.48832
3,62639,NaN,2022.149240,BaseGame,12 to under 18,0.998837,4.478198,2.401989,-2.565285,69.042747,-4.021747,9.757236,24.737626,200.847605,136.030458,39.452069,7.66071
4,26419,Shift: The Single Card CCG,1980.874850,BaseGame,5 to under 12,1.049099,2.563767,2.953464,-9.404579,118.814781,-346.308189,2.090496,-0.576344,41.042707,141.711200,-5.460189,7.50000

In [9]:
df.isnull().sum()

Game_ID                   0
Game_Name              1147
Released_Year             0
Game_Type              1141
Age_Category           1141
Min_Players               0
Max_Players               0
Average_Complexity        0
Complexity_Raters         0
Average_Play_Time         0
Owner_Number              0
Trader_Number             0
HighInterest_Number       0
Interest_Number           0
Rater_Number              0
Comment_Number            0
Average_Rating            0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(0)